### ISSUE TITLE
feature: reports page adaptive versions

### ISSUE THREAD

**Issue by thirdmadman** [thirdmadman/fond-ravnovesie.ru_2023#4]
## Task

Implement adaptive versions for the existing reports page

## Description

Follow this convention for naming commits and branches: [Link](https://dev.to/varbsan/a-simplified-convention-for-naming-branches-and-commits-in-git-il4)

**Branch name have to be**: ```feature/issue-4/reports-page-adaptive-versions```

Link to the page "/reports"

This includes:

- [x] Version for the screen width of 1920px
- [x] Version for the screen width of 1600px
- [x] Version for the screen width of 1280px
- [x] Version for the screen width of 390px
